import { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import axios from "axios";

export default function Home() {
  const [searchTerm, setSearchTerm] = useState("");

  const handleSubmit = async (e) => {
    e.preventDefault();
    try {
      const response = await axios.post("/api/shorturl", {
        url: searchTerm,
      });
      console.log(response.data);
      // Handle response from server as needed
    } catch (error) {
      console.error(error);
      // Handle error as needed
    }
  };

  const handleInputChange = (e) => {
    setSearchTerm(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Short Url</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100">
        <div className="flex justify-between items-center px-6 py-4">
          <h1 className="text-3xl font-bold text-gray-700">Google</h1>
          <div>
            <Link href="/login">
              <button className="px-4 py-2 mr-4 text-gray-700 font-medium rounded-full hover:bg-gray-200">
                Login
              </button>
            </Link>
            <Link href="/register">
              <button className="px-4 py-2 bg-blue-500 text-white font-medium rounded-full hover:bg-blue-600">
                Register
              </button>
            </Link>
          </div>
        </div>

        <div className="flex justify-center items-center h-screen">
          <form
            onSubmit={handleSubmit}
            className="bg-white rounded-lg shadow-md p-10"
          >
            <input
              type="text"
              className="w-full border border-gray-400 py-2 px-4 rounded-lg"
              placeholder="Search Google"
              value={searchTerm}
              onChange={handleInputChange}
            />
            <button
              type="submit"
              className="mt-4 bg-blue-500 text-white py-2 px-4 rounded-lg hover:bg-blue-600"
            >
              Google Search
            </button>
          </form>
        </div>
      </main>
    </>
  );
}
